substitutions:
  _SERVICE_NAME: webrtc-backend
  _REGION: us-central1
  _REPO: gcr.io/$PROJECT_ID/webrtc-backend
  _FRONTEND_URL: https://web-rtc-ai-conference-da05ulotr-igor-dev-public.vercel.app/

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build container image
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_REPO:$SHORT_SHA", "-t", "$_REPO:latest", "backend"]

  # Push image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_REPO:$SHORT_SHA"]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_REPO:latest"]

  # Deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run","deploy","$_SERVICE_NAME",
        "--image","$_REPO:$SHORT_SHA",
        "--region","$_REGION",
        "--platform","managed",
        "--allow-unauthenticated",
        "--port","8080",
        "--memory","512Mi",
        "--cpu","1",
        "--set-env-vars","NODE_ENV=production,OPENAI_API_KEY=${OPENAI_API_KEY},FRONTEND_URL=${_FRONTEND_URL}"
      ]

images:
  - "$_REPO:$SHORT_SHA"
  - "$_REPO:latest"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: OPENAI_API_KEY


